language: node_js
node_js:
  - 10.9.0

cache: npm

before_install:
  - ls -la
  - npm install
  - mkdir public
  - ls -la
  - "npm config set spin false"
  - npm i -g now

install:
  - npm install

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true

script:
  - npm run build
  - npm run test
